name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - "challenge16-ci-and-cd-for-azure-functions/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "Run npm"
        shell: bash
        run: |
          pushd challenge16-ci-and-cd-for-azure-functions
          npm ci
          npm run build --if-present
          npm run test --if-present
          popd
